import traceapp from '../content/apps/traceapp.zh.json';
import ThemeToggle from '../components/ThemeToggle';
type Section = 'overview' | 'getting-started' | 'privacy' | 'terms' | 'support';

export default function TraceAppPage({ path }: { path: string }) { const section: Section = path.includes('/getting-started/') ? 'getting-started' : path.includes('/privacy/') ? 'privacy' : path.includes('/terms/') ? 'terms' : path.includes('/support/') ? 'support' : 'overview'; return <><ThemeToggle /><TraceHeader /><main className="product-page"><div className="container product-page-inner"><nav className="breadcrumbs" aria-label="面包屑"><a href="/">首页</a><span>／</span><a href="/apps/">应用中心</a><span>／</span><span>{traceapp.appName}</span></nav><section className="product-hero"><p className="route-eyebrow">{traceapp.platformName} · {traceapp.storeName}</p><h1>{pageTitle(section)}</h1><p>{section === 'overview' ? traceapp.description : pageDescription(section)}</p><TraceTabs active={section} /></section><TraceBody section={section} /></div></main><TraceFooter /></>; }

function TraceBody({ section }: { section: Section }) { if (section === 'overview') return <><section className="content-section"><h2>让每段路程有迹可循</h2><div className="feature-grid">{traceapp.features.map((feature) => <div className="feature-card" key={feature}>{feature}</div>)}</div></section><section className="privacy-facts"><h2>本地优先，数据可控</h2><p>不需要账号，不内置广告或第三方统计。轨迹默认留在当前设备；iCloud 同步仅在你主动开启时使用。</p><div className="action-row"><a className="btn-primary" href="/apps/traceapp/getting-started/">开始使用</a><a className="btn-ghost" href="/apps/traceapp/privacy/">阅读隐私政策</a></div></section><ScreenshotGallery /></>; if (section === 'getting-started') return <section className="content-section"><h2>从第一段路开始</h2><ol className="guide-list">{traceapp.guide.map((step, index) => <li key={step.title}><span>{index + 1}</span><div><h3>{step.title}</h3><p>{step.body}</p></div></li>)}</ol></section>; if (section === 'privacy' || section === 'terms') { const document = traceapp[section]; return <article className="legal-document"><p className="legal-meta">生效日期：{document.effectiveDate} · 适用平台：{traceapp.platformName} · 应用名称：{traceapp.appName}</p>{'intro' in document && <p className="legal-intro">{document.intro}</p>}{document.sections.map((item) => <section key={item.title}><h2>{item.title}</h2>{item.body.map((paragraph) => <p key={paragraph}>{paragraph}</p>)}</section>)}<section><h2>联系我们</h2><p>如有疑问，请联系：<a href={`mailto:${document.contactEmail}`}>{document.contactEmail}</a></p></section></article>; } return <section className="content-section"><h2>技术支持</h2><div className="faq-list"><details open><summary>如何调整定位权限？</summary><p>在“设置 → 隐私与安全性 → 定位服务 → 出行轨迹”中，选择“使用 App 期间”或“始终”，也可随时关闭。</p></details><details><summary>如何删除数据？</summary><p>可在应用内删除单条或全部记录；卸载会删除本机数据。若启用 iCloud，同步副本需在 iCloud 中另行管理。</p></details><details><summary>反馈问题时应提供什么？</summary><p>建议附上复现步骤、期望与实际结果、设备型号和系统版本；可附截图，便于定位。</p></details></div><p className="support-contact">仍需帮助？请邮件联系 <a href={`mailto:${traceapp.supportEmail}`}>{traceapp.supportEmail}</a>。</p></section>; }
function ScreenshotGallery() { return <section className="screenshot-section trace-screenshot-section"><div><p className="route-eyebrow">商店截图</p><h2>路线、地图与历史回看</h2></div><div className="screenshot-strip trace-screenshot-strip">{['/apps/traceapp/shot-01.png', '/apps/traceapp/shot-02.png', '/apps/traceapp/shot-03.png'].map((image, index) => <img src={image} alt={`出行轨迹 TraceApp 界面截图 ${index + 1}`} key={image} loading="lazy" />)}</div></section>; }
function TraceTabs({ active }: { active: Section }) { const routes: Array<[Section, string]> = [['overview', '产品介绍'], ['getting-started', '新手引导'], ['privacy', '隐私政策'], ['terms', '用户协议'], ['support', '技术支持']]; return <nav className="platform-tabs page-tabs" aria-label="出行轨迹页面导航">{routes.map(([section, label]) => <a key={section} className={active === section ? 'active' : ''} href={section === 'overview' ? '/apps/traceapp/' : `/apps/traceapp/${section}/`}>{label}</a>)}</nav>; }
function TraceHeader() { return <header className="navbar"><div className="container nav-inner"><a className="brand" href="/" aria-label="上海树下小屋网络科技有限公司"><span className="brand-icon" aria-hidden="true">✦</span><span className="brand-text"><span className="cn">出行轨迹 TraceApp</span><span className="en">路线记录 · 数据可控</span></span></a><nav className="nav-menu nav-menu-static"><a href="/apps/" className="nav-link">应用中心</a><a href="/apps/traceapp/support/" className="nav-link cta-nav">技术支持</a></nav></div></header>; }
function TraceFooter() { return <footer className="site-footer"><div className="container footer-inner"><div className="footer-left"><div className="footer-brand">出行轨迹 TraceApp</div><div className="footer-slogan">产品介绍 · 新手引导 · 隐私与支持</div></div><div className="footer-right"><div className="footer-links"><a href="/apps/traceapp/privacy/">隐私政策</a><a href="/apps/traceapp/terms/">用户协议</a></div></div></div></footer>; }
function pageTitle(section: Section) { return section === 'overview' ? traceapp.tagline : section === 'getting-started' ? '出行轨迹 TraceApp 新手引导' : section === 'privacy' ? '出行轨迹 TraceApp 隐私政策' : section === 'terms' ? '出行轨迹 TraceApp 用户协议' : '出行轨迹 TraceApp 技术支持'; }
function pageDescription(section: Section) { return section === 'getting-started' ? '从定位权限到回看路线，快速开始。' : section === 'privacy' ? '了解轨迹数据、iCloud 与系统权限如何被处理。' : section === 'terms' ? '请在使用本应用前阅读用户协议。' : '帮助你顺利记录和管理每一段出行。'; }
